version: '3.8'

services:
  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/train.py

  serve:
    build:
      context: .
      dockerfile: docker/Dockerfile.serve
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=models/latest_model.pkl
    depends_on:
      - train
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development environment
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/bash
    stdin_open: true
    tty: true